### ISSUE TITLE
how do i start?

### ISSUE THREAD

**Issue by silvergravel** [dalmirdasilva/ArduinoCamera#1]
Hi dalmirdasilva,
firstly im a noob when it comes to arduino so please bear with me. i currently have a ov7670 camera which i want to interface with my arduino. just get it sending out some signal at least! i have read a bunch of posts from my_arduino and many others, but im just not knowledgable enough to make sense out of all of it. If you could somehow guide me as to how i could use your library, then that would be great! any sort of pointers or hints as to how i must move forward would be really helpful!

thanks

**Comment by dalmirdasilva** [comment]
Hi silvergravel, glad you are interested. Actually I had the 7670 camera, but it broke it and I never bought again. I bought the VC0706 one, which is easier to wire up and get things done with. The libraries here, except for the VC0706 camera, are something like draft which should be improved someday; Only the VC0706 library is actually working, the others I abandoned because I don't have the hardware to test them. They still here because can help someone and also someone could improve them.

I suggest you to start with the VC0706, that one uses serial communication, which is a easier communication than the others.

If you go any further than me, please send a pull request to help other people out there.

Have fun and good luck.

**Comment by silvergravel** [comment]
thanks a lot for your reply dalmirdasilva. Its going to be a while till I start working on the ov7670 again, or as you suggested vc0706. but yes if i get further than you, il be sure to post it here.

Thanks again.
